### ISSUE TITLE
Plugin Request: Lidarr (Smells like Sonarr but made for music)

### ISSUE THREAD

**Issue by ChaosBlades** [freenas/iocage-ix-plugins#118]
We have Sonarr (TV) and Radarr (Movies). We just need something for music. Lidarr is a fork of Sonarr just like Radarr is and they have instructions on the Github for FreeNAS/FreeBSD.

https://github.com/lidarr/Lidarr

**Comment by miwi-fbsd** [comment]
Hello, We have moved community plugins to https://github.com/ix-plugin-hub/iocage-plugin-index, can u please reopen the plugin request there. Thanks.
