### ISSUE TITLE
Plugin Request: Jackett (API Support for your favorite torrent trackers)

### ISSUE THREAD

**Issue by ChaosBlades** [freenas/iocage-ix-plugins#119]
"Jackett works as a proxy server: it translates queries from apps (Sonarr, Radarr, SickRage, CouchPotato, Mylar, Lidarr, DuckieTV, qBittorrent, Nefarious etc) into tracker-site-specific http queries, parses the html response, then sends results back to the requesting software. This allows for getting recent uploads (like RSS) and performing searches. Jackett is a single repository of maintained indexer scraping & translation logic - removing the burden from other apps."

They don't have specific instructions on installing on FreeNAS/FreeBSD but they do have the start script. I have had this running in a FreeNAS Jail before all the warden to iocage stuff happened and I had no problems with it.

https://github.com/Jackett/Jackett

**Comment by miwi-fbsd** [comment]
Hello, We have moved community plugins to https://github.com/ix-plugin-hub/iocage-plugin-index, can u please reopen the plugin request there. Thanks.
