### ISSUE TITLE
General Repo Questions

### ISSUE THREAD

**Issue by josh4trunks** [freenas/iocage-ix-plugins#131]
Hi, feel free to close this non-issue, just wanted to start a disucssion and wasn't sure the best place/person to talk to. I helped write maintain many of the plugins for FreeNAS9 (when they were the difficult to build PBIs). I just read up on the new procedure here https://www.ixsystems.com/community/resources/create-an-unofficial-iocage-plugin.99/, created a test FreeNAS 11.2 system, and loving the simplicity of everything so far.

I was planning on starting to contribute changes/ new plugins sometime in the future (if I ever find the time with my 9-month old son). But had a few questions...
1. Why do some of the plugins in this repo not show in the "Available" list in FreeNAS? For example sabnzbd.json is in this repo. I did notice the artifact link did not work.
2. Is there a good way to include custom ports? For example I want to develop a medusa or sickchill plugin, can write a port for it, but don't necessarily know when it will be accepted in the FreeBSD repo.
3. Is there a good way to set build options for dependencies? For example emby/subsonic should have LAME enabled in ffmpeg, but my understanding is iocage will just pull the vanilla package from the prescribed repo.

Thank you!

**Comment by josh4trunks** [comment]
@miwi-fbsd 
This seems pretty hacky but I'm thinking to solve 2 and 3 I could just include custom pkgs in the artifact directory that can be installed during post-install. It should work as long as the plugin jail OS is generally the same version. Another option is including the port source, but that would mean building it on users systems which creates even more opportunity for failure during installation.

**Comment by miwi-fbsd** [comment]
Hi Josh,

> Hi, feel free to close this non-issue, just wanted to start a disucssion and wasn't sure the best place/person to talk to. I helped write maintain many of the plugins for FreeNAS9 (when they were the difficult to build PBIs). I just read up on the new procedure here https://www.ixsystems.com/community/resources/create-an-unofficial-iocage-plugin.99/, created a test FreeNAS 11.2 system, and loving the simplicity of everything so far.
> 
> I was planning on starting to contribute changes/ new plugins sometime in the future (if I ever find the time with my 9-month old son). But had a few questions...
Hehe, congrats :) I know how that feels!

> 
> 1. Why do some of the plugins in this repo not show in the "Available" list in FreeNAS? For example sabnzbd.json is in this repo. I did notice the artifact link did not work.

The plan was to complete the plugin at one point, back then iocage was not able to handle different
index urls so for testing we added it. 


> 2. Is there a good way to include custom ports? For example I want to develop a medusa or sickchill plugin, can write a port for it, but don't necessarily know when it will be accepted in the FreeBSD repo.

sickchill should be removed, we have sickrage as a replacement. Generally we have our own ports tree and can add new ports directly but of coz prefer way to get it to FreeBSD. I am surely willing to help with this part. 

> 3. Is there a good way to set build options for dependencies? For example emby/subsonic should have LAME enabled in ffmpeg, but my understanding is iocage will just pull the vanilla package from the prescribed repo.

I agree with you on the LAME part but, its a restricted license and not allowed to be distributed as a package. I'd not to provoke any kind of issues for IX when we do it.

> 
> Thank you!

Hope that helps :-)

**Comment by josh4trunks** [comment]
@miwi-fbsd thank you for the response! Here's a few more followup things on the points numbered above.

1. maybe I can help if I find time.
2. Not sure if you are just preferring SickRage, or you aren't aware of the drama that happened in October 2018. My understanding is SickChill sort of replaced SickRage, I am not sure many people actually still use SickRage since then. Sounds like a good plan with custom ports, 
3.Makes sense for LAME. But what about other (I believe not restricted) options like H265 for the subsonic plugin? I am pretty sure H265 just happens to be off by default in ffmpeg.

**Comment by miwi-fbsd** [comment]
> @miwi-fbsd thank you for the response! Here's a few more followup things on the points numbered above.
> 
> 1. maybe I can help if I find time.
Would be very much appreciated :-)

> 2. Not sure if you are just preferring SickRage, or you aren't aware of the drama that happened in October 2018. My understanding is SickChill sort of replaced SickRage, I am not sure many people actually still use SickRage since then. Sounds like a good plan with custom ports.

Ey, sorry my bad yes i am aware of that i keep on mixing up the both names! Sorry about that.

>    3.Makes sense for LAME. But what about other (I believe not restricted) options like H265 for the subsonic plugin? I am pretty sure H265 just happens to be off by default in ffmpeg.

H265 is fine. I can enable it for the next build.

**Comment by josh4trunks** [comment]
No rush enabling H265, it's not that relevant to subsonic; just wanted to think of an example. I'm sure there are many other options that would be preferred to be enabled as I contribute in development. I assume these are just enabled in the custom pkg repo?

**Comment by miwi-fbsd** [comment]
Yes, please let me know what you'd like to have enabled, to be honest, i'd prefer the default package way for security reason, the more we enable on flags, the more we risk to being vulnerable.

**Comment by josh4trunks** [comment]
Sounds, good. Ok thank you for the help!
I'll close this issue and hope to provide some plugins in the future.
