### ISSUE TITLE
Gitlab Plugin : Not showing up... 

### ISSUE THREAD

**Issue by mairod** [freenas/iocage-ix-plugins#154]
Gitlab plugin is not showing up il the list of avaliable plugins, but every else plugins is. I don't understand why. 
I'm using `FreeNAS-11.2-U5`, is that normal ? 

![Capture](https://user-images.githubusercontent.com/17464559/65498311-f4debf00-debb-11e9-918a-dc1e9f0130fc.PNG)

**Comment by miwi-fbsd** [comment]
Hi,

Yes we have disabled it at the moment because we found some issues.

**Comment by ladal1** [comment]
Any timeline on when it could be readded?
Thanks

**Comment by dlavigne** [comment]
It is fixed for 11.3. BETA1 is due out this week.
