### ISSUE TITLE
Update to FreeBSD 11.1-RELEASE

### ISSUE THREAD

**Issue by alexjj** [freenas/iocage-ix-plugins#2]
When will these plugins be updated to the latest release? What do they depend on before this can occur?

Thanks.

**Comment by skarekrow** [comment]
Sorry didn't see this issue! They've been updated :)

**Comment by justinclift** [comment]
@skarekrow Maybe add yourself to the watch list for the repo? :smile:

**Comment by skarekrow** [comment]
@justinclift D’oh! :D
