### ISSUE TITLE
qbittorrent - can't install search plugins

### ISSUE THREAD

**Issue by B3DTech** [freenas/iocage-ix-plugins#201]
Attempting to install a search plugin by copy/pasting the link to the python file, it does absolutely nothing.  Latest versions of FreeNas/qbittorrent plugin.

**Comment by NorthernMunkey** [comment]
agreed, either copying the .py locally and referencing or pointing it to a url produces same results.
maybe it can't write to an area in the jail to make the changes?

**Comment by Lokarde** [comment]
A solution is to use rc.conf to start the plugin instead of rc.local
Comment qbittorrent line in rc.local and add qbittorrent_enable="YES" in rc.conf file

**Comment by sonicaj** [comment]
qbittorrent is not an official plugin. Please report any issues regarding it at http://github.com/ix-plugin-hub/iocage-plugin-index/. Thank you
