### ISSUE TITLE
Plex name

### ISSUE THREAD

**Issue by darkfiberiru** [freenas/iocage-ix-plugins#202]
Iocage doesn't seem to like that the plex name is plex while the file is plexmediaserver.json not plex.json.  Renaming plugin in config file(iocage set plugin=plexmediaserver plex) seemed to fix the issue.

Not sure if the upgrade command is the only corner case here or why were not seeing this more.
 
> 
> 
> freenas-primary% sudo iocage upgrade -r 11.3-RELEASE plex
> Snapshotting plex...
> Updating plugin INDEX...
> Traceback (most recent call last):
>   File "/usr/local/bin/iocage", line 10, in <module>
>     sys.exit(cli())
>   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/iocage_cli/upgrade.py", line 40, in cli
>     ioc.IOCage(jail=jail, skip_jails=skip_jails).upgrade(release)
>   File "/usr/local/lib/python3.7/site-packages/iocage_lib/iocage.py", line 2065, in upgrade
>     ).upgrade(jid)
>   File "/usr/local/lib/python3.7/site-packages/iocage_lib/ioc_plugin.py", line 1251, in upgrade
>     self.iocroot, 'jails', self.jail, f'{plugin_name}.json'
>   File "/usr/local/lib/python3.7/shutil.py", line 248, in copy
>     copyfile(src, dst, follow_symlinks=follow_symlinks)
>   File "/usr/local/lib/python3.7/shutil.py", line 120, in copyfile
>     with open(src, 'rb') as fsrc:
> FileNotFoundError: [Errno 2] No such file or directory: '/mnt/storage/iocage/.plugins/github_com_freenas_iocage-ix-plugins_git/plex.json'
> freenas-primary% cd /mnt/storage/iocage/.plugins/github_com_freenas_iocage-ix-plugins_git/
>

**Comment by miwi-fbsd** [comment]
Can you please check if that is still the case?

**Comment by darkfiberiru** [comment]
@miwi-fbsd Is 11.3-rc2 new enough for me to test with?

**Comment by kmoore134** [comment]
@darkfiberiru go ahead and retest with rc2
