### ISSUE TITLE
Nextcloud 17 - Upgrade to PHP7.2

### ISSUE THREAD

**Issue by Fiddledeedee0** [freenas/iocage-ix-plugins#203]
Hi

Some of the new plugins such as 2FA require PHP7.2 to work. Currently plugin install PHP7.1, not really huge deal but breaks 2FA TOTP to be specific. 

Would this require upstream to update nextcloud-php71 to nextcloudphp72 or just changes to Artifact file to install PHP7.2 instead of 7.1?

The below script installs 7.2 by default which works greats but personally still using plugin version due to fact currently I cant find a fix for having caddy just working as HTTP. 

https://www.ixsystems.com/community/threads/scripted-installation-of-nextcloud-17-in-iocage-jail.62485

Thanks

**Comment by miwi-fbsd** [comment]
Hi @Fiddledeedee0,

I am aware of this issue. Also PHP7.1 is EOL and removed from the FreeBSD ports collection. For the January update I plan to bring it up to 7.2/

**Comment by Fiddledeedee0** [comment]
> 
> 
> Hi @Fiddledeedee0,
> 
> I am aware of this issue. Also PHP7.1 is EOL and removed from the FreeBSD ports collection. For the January update I plan to bring it up to 7.2.

Good to know!

Look forward to the update.
