### ISSUE TITLE
Qbittorrent monitored folder path not saving

### ISSUE THREAD

**Issue by NorthernMunkey** [freenas/iocage-ix-plugins#210]
within the settings you can apply a monitored forlder location,  this doesn't seem to be saving.

Looking in the jail .config/qBittorrent/qBittorrent.conf
there is a line i think is to do with it
Downloads\ScanDirsV2=@Variant (\0\0\0\x1c\0\0\0\0)

not sure what @Variant (\0\0\0\x1c\0\0\0\0)  is

**Comment by sonicaj** [comment]
qbittorrent is not an official plugin. Please report any issues regarding it at http://github.com/ix-plugin-hub/iocage-plugin-index/. Thank you
