### ISSUE TITLE
Zoneminder API CakePHP Error

### ISSUE THREAD

**Issue by bignellrp** [freenas/iocage-ix-plugins#214]
zm/api gives the following error.

`Missing Controller
Error: ZmController could not be found.
Error: Create the class ZmController below in file: app/Controller/ZmController.php
<?php
class ZmController extends AppController {
}`

A few people reporting the same issue on the zoneminder forums but no fix reported.

https://forums.zoneminder.com/viewtopic.php?f=38&t=28189

ZMController.php just appears to be missing

root@zoneminder:/usr/local/www/zoneminder/api/app/Controller # ls -la
total 129
drwxr-xr-x 3 www www 19 Mar 11 13:26 .
drwxr-xr-x 11 www www 12 Mar 13 11:44 ..
-rw-r--r-- 1 www www 3694 Dec 8 2018 AppController.php
drwxr-xr-x 2 www www 6 Mar 11 13:26 Component
-rw-r--r-- 1 www www 3270 Dec 8 2018 ConfigsController.php
-rw-r--r-- 1 www www 1353 Dec 8 2018 ControlsController.php
-rw-r--r-- 1 www www 12162 Dec 8 2018 EventsController.php
-rw-r--r-- 1 www www 2516 Dec 8 2018 FramesController.php
-rw-r--r-- 1 www www 3472 Dec 8 2018 GroupsController.php
-rw-r--r-- 1 www www 5584 Dec 8 2018 HostController.php
-rw-r--r-- 1 www www 2383 Dec 8 2018 LogsController.php
-rw-r--r-- 1 www www 11289 Dec 8 2018 MonitorsController.php
-rw-r--r-- 1 www www 2123 Dec 8 2018 PagesController.php
-rw-r--r-- 1 www www 3697 Dec 8 2018 ServersController.php
-rw-r--r-- 1 www www 3646 Dec 8 2018 StatesController.php
-rw-r--r-- 1 www www 3776 Dec 8 2018 StorageController.php
-rw-r--r-- 1 www www 3777 Dec 8 2018 UsersController.php
-rw-r--r-- 1 www www 2654 Dec 8 2018 ZonePresetsController.php
-rw-r--r-- 1 www www 4608 Dec 8 2018 ZonesController.php

**Comment by sonicaj** [comment]
Zoneminder is not an official plugin. Please report any issues regarding it at http://github.com/ix-plugin-hub/iocage-plugin-index/. Thank you
