### ISSUE TITLE
Please help to update the plug-in to lastest version 4.2.1

### ISSUE THREAD

**Issue by cola2050** [freenas/iocage-ix-plugins#215]
hi sir

   qbittorent4.2.1 is the most stable, the fastest. supported ipv6, and the parameters can be modified in web-gui
    Please help to update the plug-in to lastest version 4.2.1, thank you.

Chris Yan

**Comment by sonicaj** [comment]
qbittorrent is not an official plugin. Please report any issues regarding it at http://github.com/ix-plugin-hub/iocage-plugin-index/. Thank you
