### ISSUE TITLE
gitlab plugin FreeNas -11.3-U2.1

### ISSUE THREAD

**Issue by fahadshery** [freenas/iocage-ix-plugins#230]
Hi,

I can no longer see the GitLab server and the runner in the list of the available plugins. Will they be coming back and by when?

tvm

**Comment by sionicion** [comment]
Yeah what's going on with Gitlab?

**Comment by MichelMelhem** [comment]
same question

**Comment by edm00se** [comment]
I'm on 11.3-U2.1 and I can see GitLab available under the "community" section of plugins, as opposed to the official ("iXsystems").

<img width="1410" alt="Pasted_Image_7_30_20__1_53_PM" src="https://user-images.githubusercontent.com/622118/88962617-4db17d80-d26c-11ea-827d-2d5857dde3af.png">

**Comment by fahadshery** [comment]
yeah, and this doesn't work. Get a 404 error

**Comment by pandorixtech** [comment]
Hi folks , is this a problem still ?

**Comment by sonicaj** [comment]
Gitlab is not an official plugin. Please report any issues regarding it at http://github.com/ix-plugin-hub/iocage-plugin-index/. Thank you
