### ISSUE TITLE
Plex Update

### ISSUE THREAD

**Issue by djryan012** [freenas/iocage-ix-plugins#231]
On my plex server I am getting this message popup "A Plex Media Server update is available for the server Plex Server! 1.19.2.2737, Download now, Skip this version"

Is it possible to update the plex plugin to use the latest software?

**Comment by kmoore134** [comment]
The packages for Plex on BSD tend to lag 3-7 days behind what plex will start notifying about. However once they are available, in the FreeNAS UI you should be able to do the upgrade.
