### ISSUE TITLE
qbittorrent Exit-qbittorrent

### ISSUE THREAD

**Issue by GogoAkira** [freenas/iocage-ix-plugins#255]
idk why I did it but before I was about to reboot TrueNAS I hit File Exit qbittorrent and now all of the torrents are gone. Also the download path is now //Downloads where before was /root/root/Downloads and now it changed to /root/Downloads.

I noticed this download default directory changed the few times I reinstalled the jail plugin but this is the first time I see the directory changed without reinstall, I guess that is why the torrent files are gone, will change the default dir and see what happens. 

Well torrent files are gone but after changing the directory it does resume where it left of after adding the torrent files again.

Settings are also reset to default

**Comment by sonicaj** [comment]
qbittorrent is not an official plugin. Please report any issues regarding it at http://github.com/ix-plugin-hub/iocage-plugin-index/

**Comment by sonicaj** [comment]
qbittorrent is not an official plugin. Please report any issues regarding it at http://github.com/ix-plugin-hub/iocage-plugin-index/

**Comment by sonicaj** [comment]
qbittorrent is not an official plugin. Please report any issues regarding it at http://github.com/ix-plugin-hub/iocage-plugin-index/. Thank you
