### ISSUE TITLE
GitLab 404 Error

### ISSUE THREAD

**Issue by JamesKBowler** [freenas/iocage-ix-plugins#262]
Version: FreeNAS-11.3-U4.1
Release: 11.3-RELEASE-p14

Clean install of FreeNas, fully updated.

404 Error when browsing to GitLab. Looks like the pkg failed to download and install because the gitlab-ce folder is missing.

Any ideas?

**Comment by leothelocust** [comment]
I have this issue too, but I'm using TrueNAS-12.0-STABLE.

**Comment by pandorixtech** [comment]
is this still happening?

**Comment by sonicaj** [comment]
Gitlab is not in the offiical plugins anymore
