### ISSUE TITLE
[求助]我设置了 https的证书后 无法打开页面了 如何找到配置文件

### ISSUE THREAD

**Issue by cnhap** [freenas/iocage-ix-plugins#267]
我设置了 https的证书后 无法打开页面了 如何找到配置文件
现在用 http://192.168.10:8080 可以弹出 登陆界面  输入账号密码后  会调转到 https://192.168.1.10:8080   但网页无法显示.求助 如何还原

**Comment by sonicaj** [comment]
qbittorrent is not an official plugin. Please report any issues regarding it at http://github.com/ix-plugin-hub/iocage-plugin-index/

**Comment by sonicaj** [comment]
qbittorrent is not an official plugin. Please report any issues regarding it at http://github.com/ix-plugin-hub/iocage-plugin-index/
