### ISSUE TITLE
Dnsmasq logo need alpha channel?

### ISSUE THREAD

**Issue by justinclift** [freenas/iocage-ix-plugins#268]
Just noticed Dnsmasq in the list of Community plugins for FreeNAS.  Cool. :smile:

The [logo](https://github.com/freenas/iocage-ix-plugins/blob/master/icons/dnsmasq.png) though seems a bit off for dark themed UI's, as it has a hard coded white background.  Guessing it's just a missing alpha channel, though I haven't yet looked properly.

That being said, would using an SVG be acceptable instead of a PNG?

I **think** the original icon created for Dnsmasq (SVG format) is still kicking around in my archives somewhere.  Can try digging that up if it'd be useful.

CC @timsavage for awareness. :smile:

**Comment by kmoore134** [comment]
I think an SVG would work, however we've only done PNG's thus far, so if something goes bad we may need to replace it with png again with the proper transparency.

**Comment by justinclift** [comment]
No worries, sounds like a workable approach.

Looking through my archives, I'm not finding the SVG I was thinking of.  So I've emailed Simon (Dnsmasq maintainer), to see if he still has the original file.  Hopefully that'll work out. :smile:

**Comment by justinclift** [comment]
Closing this, as the PR to switch to an SVG file (https://github.com/ix-plugin-hub/iocage-plugin-index/pull/149) has been merged. :smile:
