### ISSUE TITLE
No soup for you! You do not have access to this server

### ISSUE THREAD

**Issue by Ming-A** [freenas/iocage-ix-plugins#272]
I left the install to default and when I press on managed in plugins to set it up and logged in it says 'No soup for you!
You do not have access to this server'

**Comment by sonicaj** [comment]
@Ming-A can you please clarify which plugin you are referring to ? Thank you

**Comment by Ming-A** [comment]
Sorry, I'm using the official Plex plugin

**Comment by sonicaj** [comment]
Interesting, i have not been able to reproduce this with a fresh install. To confirm, you are getting this after a fresh install of the plex plugin ?

**Comment by Ming-A** [comment]
> Interesting, i have not been able to reproduce this with a fresh install. To confirm, you are getting this after a fresh install of the plex plugin ?

yes, I have reinstalled it a few time, uninstalling it then reinstalling and logging into an account which would take me to this site, have used different accounts too with same error 
![image](https://user-images.githubusercontent.com/41011175/107942775-af49f700-6fc6-11eb-9c27-116a994677c7.png)

**Comment by StoneMonarch** [comment]
Any chances that you are running the Plex server on a different network than the machine you are trying to access it from? I had this problem when setting up the server before on a separate VLAN. Plex seems to like local Class C IPs for setup. Try putting yourself onto the same LAN and you should be able to get it to work

**Comment by Ming-A** [comment]
> @Ming-A Any chances that you are running the Plex server on a different network than the machine you are trying to access it from? I had this problem when setting up the server before on a separate VLAN. Plex seems to like local Class C IPs for setup. If this is the case, try putting yourself onto the same LAN and you should be able to get it to work

this solved it, I set a VM to have the same port and I now have access to setup. Thanks for the help
