### ISSUE TITLE
Monica plugin failing on install. 

### ISSUE THREAD

**Issue by jim9835** [freenas/iocage-ix-plugins#273]
Hi

Am running TrueNAS-12.0-U1. Monica install is failing:

![107879031-5bf47d80-6ece-11eb-9e1d-2aecb89f5b72.png](https://user-images.githubusercontent.com/52280787/107947420-43e23400-6f8a-11eb-94bf-d4f6d219e33e.png)

Is this the place to report it?

Thanks

**Comment by sonicaj** [comment]
Monica is not an official plugin. Please report any issues regarding it at http://github.com/ix-plugin-hub/iocage-plugin-index/. Thank you
