### ISSUE TITLE
FreeBSD 12.1 has reached end of life.

### ISSUE THREAD

**Issue by NikkuFox** [freenas/iocage-ix-plugins#274]
FreeBSD 12.1 reached end of life on 31st Jan 2021, but all the plugins are still configured to use `12.1-RELEASE`.

**Comment by verdsveven** [comment]
I second this.

**Comment by verdsveven** [comment]
Any updates regarding this?

**Comment by kmoore134** [comment]
@verdsveven go ahead and make a pull-request, it should be safe to just bulk change the version to 12.2-RELEASE

**Comment by verdsveven** [comment]
@kmoore134 Sure, I'll do it if you say it's safe for all plugins.

**Comment by verdsveven** [comment]
@kmoore134 Should I do it for the 12.2-RELEASE and master branch?

**Comment by kmoore134** [comment]
Master first, and then we'll do a backport PR until 12.2-RELEASE :)

Thanks!

**Comment by verdsveven** [comment]
@kmoore134 Done: #276
