### ISSUE TITLE
Nextcloud MySQL Version is reaching end of support by Nextcloud

### ISSUE THREAD

**Issue by Phaeton20** [freenas/iocage-ix-plugins#278]
Nextcloud MySQL Version is reaching end of support by Nextcloud

**Comment by verdsveven** [comment]
I second this issue @Phaeton20. This change is already in the master branch i.e. not in 12.2-RELEASE. However, a pull request has already been made by @kmoore134 to backport these changes into 12.2-RELEASE. It is currently awaiting review.

**Comment by Phaeton20** [comment]
OK than its being handeld. I just stumbled above the warning after installing nextcloud fresh.

**Comment by sonicaj** [comment]
The changes have been merged to 12.2.
