### ISSUE TITLE
NextCloud - MYSQL 8 installation error

### ISSUE THREAD

**Issue by aitorhergon** [freenas/iocage-ix-plugins#284]
Hello,
When you try to perform a NextCloud installation it gives an error in the database and user creation syntax.

TrueNas Version: 12.0-U3
Nexcloud Plugin Version: 21.0.1
Mysql Version: 8.0.23 for FreeBSD12.2 on amd64 
-----------------------------------------------------------------------
Example of error:

nginx_enable: -> YES

mysql_enable: -> YES

php_fpm_enable: -> YES

Performing sanity check on nginx configuration:

Starting nginx.

Performing sanity check on php-fpm configuration:

Starting php_fpm.

Starting mysql.

Starting mysql.

**ERROR 1064** (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '('TcXe4HehSuHzqUHd') WHERE User='root'' at line 1

Using NAT Address: 192.168.0.130

ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '('TcXe4HehSuHzqUHd') WHERE User='root'' at line 1

Error while trying to create admin user: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'dbadmin'@'localhost' (using password: YES)

Trace: #0 /usr/local/www/nextcloud/lib/private/DB/ConnectionAdapter.php(69): OC\DB\Exceptions\DbalException::wrap()

#1 /usr/local/www/nextcloud/lib/private/DB/MySqlTools.php(60): OC\DB\ConnectionAdapter->executeQuery()

#2 /usr/local/www/nextcloud/lib/private/DB/MySqlTools.php(40): OC\DB\MySqlTools->isMariaDBWithLargePrefix()

#3 /usr/local/www/nextcloud/lib/private/Setup/MySQL.php(50): OC\DB\MySqlTools->supports4ByteCharset()

#4 /usr/local/www/nextcloud/lib/private/Setup.php(360): OC\Setup\MySQL->setupDatabase()

#5 /usr/local/www/nextcloud/core/Command/Maintenance/Install.php(108): OC\Setup->install()

#6 /usr/local/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Maintenance\Install->execute()

#7 /usr/local/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()

#8 /usr/local/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()

#9 /usr/local/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()

#10 /usr/local/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()

#11 /usr/local/www/nextcloud/console.php(100): OC\Console\Application->run()

#12 /usr/local/www/nextcloud/occ(11): require_once('/usr/local/www/...')

#13 {main}

Previous: Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [1045] Access denied for user 'dbadmin'@'localhost' (using password: YES)

Trace: #0 /usr/local/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1486): OC\DB\Connection->connect()

#1 /usr/local/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1014): Doctrine\DBAL\Connection->getWrappedConnection()

#2 /usr/local/www/nextcloud/lib/private/DB/Connection.php(226): Doctrine\DBAL\Connection->executeQuery()

#3 /usr/local/www/nextcloud/lib/private/DB/ConnectionAdapter.php(66): OC\DB\Connection->executeQuery()

#4 /usr/local/www/nextcloud/lib/private/DB/MySqlTools.php(60): OC\DB\ConnectionAdapter->executeQuery()

#5 /usr/local/www/nextcloud/lib/private/DB/MySqlTools.php(40): OC\DB\MySqlTools->isMariaDBWithLargePrefix()

#6 /usr/local/www/nextcloud/lib/private/Setup/MySQL.php(50): OC\DB\MySqlTools->supports4ByteCharset()

#7 /usr/local/www/nextcloud/lib/private/Setup.php(360): OC\Setup\MySQL->setupDatabase()

#8 /usr/local/www/nextcloud/core/Command/Maintenance/Install.php(108): OC\Setup->install()

#9 /usr/local/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Maintenance\Install->execute()

#10 /usr/local/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()

#11 /usr/local/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()

#12 /usr/local/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()

#13 /usr/local/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()

#14 /usr/local/www/nextcloud/console.php(100): OC\Console\Application->run()

#15 /usr/local/www/nextcloud/occ(11): require_once('/usr/local/www/...')

#16 {main}

ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '('TcXe4HehSuHzqUHd') WHERE User='root'' at line 1

Nextcloud is not installed - only a limited number of commands are available

ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '('TcXe4HehSuHzqUHd') WHERE User='root'' at line 1

Nextcloud is not installed - only a limited number of commands are available

Nextcloud is not installed - only a limited number of commands are available

There are no commands defined in the "config:system" namespace.

Nextcloud is not installed - only a limited number of commands are available

There are no commands defined in the "config:system" namespace.

Nextcloud is not installed - only a limited number of commands are available

Nextcloud is not installed - only a limited number of commands are available

There are no commands defined in the "db" namespace.

Performing sanity check on php-fpm configuration:

There are no commands defined in the "db" namespace.

Stopping php_fpm.

There are no commands defined in the "db" namespace.

There are no commands defined in the "db" namespace.

Waiting for PIDS: 6654.

There are no commands defined in the "db" namespace.

Performing sanity check on php-fpm configuration:

There are no commands defined in the "db" namespace.

Starting php_fpm.

There are no commands defined in the "db" namespace.

Performing sanity check on nginx configuration:

There are no commands defined in the "db" namespace.

Stopping nginx.

There are no commands defined in the "db" namespace.

There are no commands defined in the "db" namespace.

There are no commands defined in the "db" namespace.

Waiting for PIDS: 6643, 6643.

There are no commands defined in the "db" namespace.

Performing sanity check on nginx configuration:

There are no commands defined in the "db" namespace.

Starting nginx.

There are no commands defined in the "db" namespace.

**Comment by kthanigaivel** [comment]
same error here

**Comment by jedthe3rd** [comment]
Looks like the current install script doesn't support MySQL 8.0... They recently updated the mysql version from 5.7 in the 12.2 release.

**Comment by molassekoenig** [comment]
Hi, having the same error. Sadly I updated my (working) older version  of the plugin, which than did not work anymor. Thus I deleted this Plugin/Jail and installed the new from scratch . Disapointingly I run into this error (ERROR 1064 (42000).
Any solution to this?? Is there a way, to install an erarlier working version of the plugin (if yes how??) or will this issue be fixed soon? I don't understand, why a 'non-working' version is supported in the Plugins. But I appreciate any help as am absolutely depending on my nextcloud, which is not working anymore. Any help is very much appreciated....Kind regards, BP

**Comment by ccodykid** [comment]
Same error here

**Comment by molassekoenig** [comment]
any solution or fix yet??

**Comment by Konrad162** [comment]
Same error

**Comment by imsorrywhat** [comment]
Also encountering this error when trying to install Nextcloud; seems like the plugin is broken.
