### ISSUE TITLE
Please remove these plugins as "officially supported" 

### ISSUE THREAD

**Issue by bitshiftnetau** [freenas/iocage-ix-plugins#297]
With the greatest respect, it's clear these plugins receive very little support and that's actually fine. You can only do so much and TrueNAS Core/Scale is a masterpiece which requires the full attention of everyone involved.

Please just remove them. The average user is perfectly capable of running up a jail and installing what we need. What we don't need or appreciate is being led down the garden path. 

In fact removing all of the plugins, official and community, would be a prudent move. They're so broken it only damages the brand at this point. 

Not one single community plugin works (ok actually only one) and now we've just discovered that setting a static IP without NAT to NextCloud makes it go all wonky... for obvious reasons. It's a security issue to fix it so why bother? Just making unnecessary work for yourselves and making promises you can't realistically hope to deliver.

Either remove them, support them properly (which includes greater test coverage and docs), or keep them and make it known the inherent instability therein... but please commit to a decision.

**Comment by william-gr** [comment]
It might not work for you, but it definitely works for a lot of people. Might not be great and have a lot of flaws but it can be used.

I suggest you to create tickets for specific issues you're facing.

**Comment by bitshiftnetau** [comment]
😂😂😂 are you fucking kidding me? Wow... 

Why assign ppl to the other thread, direct me here, then tell me this? Why not just tell me that on the other thread?

There are only 3 active tickets on this hub and they date back to 2018. Don't kid yourself, the plugins aren't being supported. Where they are, it's obviously not done very well and I've tried to be nice about that but you're getting your back up so you can have both barrels.

You don't test them properly either so don't give me this garbage about them not being great and having a lot of flaws as if that's some inexorable outcome. There are always edge cases sure, but I'm referring to core functionality.

Trying to give you some real talk here and all you've got is gaslighting? You'll have to do better than that son. This isn't my first rodeo. 

You're actively damaging your brand and the brands of the 'plugins' by creating an unnecessary layer of maintenance. From a business sense you're only creating more overhead for no real reason. 

What a disappointing response. I expected better. 

Fine. It doesn't benefit me in literally any way, have your sunk cost fallacy and your false advertising. 

I'll just have to do my part in spreading the word seeing as you're only too happy wasting ppl's time.
