### ISSUE TITLE
Error upgrading on Truenas

### ISSUE THREAD

**Issue by arthurvanzyl** [freenas/iocage-ix-plugins#305]
I am unable to upgrade either via the Truenas plugin or admin screen. I go to the admin URL I get  "Nextcloud will be updated to version 23.0.0" Click update and I only get an error message with no description. 

Update to 23.0.0

An error occurred.
Detailed logs 
Please reload the page.

The detailed log only shows "An error occurred."

Any advice ?

Thanks Arthur

**Comment by sonicaj** [comment]
@arthurvanzyl can you please create a ticket at https://jira.ixsystems.com and kindly make sure to upload a debug of your system ( System -> Advanced -> Save Debug ) right after reproducing the problem. Screenshots would also be nice as i think the nextcloud plugin upgrades but the upgrade within nextcloud plugin is erroring out for you when you click upgrade from it's UI. Thanks!

**Comment by arthurvanzyl** [comment]
Thanks @sonicaj - Here is my ticket reference number: https://jira.ixsystems.com/browse/NAS-114115
