### ISSUE TITLE
qbittorrent runs as root

### ISSUE THREAD

**Issue by jcassette** [freenas/iocage-ix-plugins#307]

**Comment by sonicaj** [comment]
@jcassette we don't have qbittorrnet in official repository, please create an issue at https://github.com/ix-plugin-hub/iocage-plugin-index or https://github.com/freenas/iocage-plugin-qbittorrent. Changes there are welcome as well ;) Thanks!

**Comment by jcassette** [comment]
Okay but it's confusing that the plugin is hosted under this account and not ix-plugin-hub then.
Also issues cannot be created at https://github.com/freenas/iocage-plugin-qbittorrent.
