### ISSUE TITLE
plugins 

### ISSUE THREAD

**Issue by deepul80** [freenas/iocage-ix-plugins#310]
my truenas server plugins i'm uable to use my plugins please fix that issue 
![Screenshot 2022-03-19 204754](https://user-images.githubusercontent.com/101851840/159126951-91ca99a3-bab2-4b97-af45-faeaad2521d7.jpg)

**Comment by sonicaj** [comment]
@deepul80 it seems like you have networking issues. Can you resolve github.com from host ?
And if yes, can you please create a ticket at https://jira.ixsystems.com ? Thanks!

**Comment by zorglube** [comment]
Looks like *your* `DNS` is KO.

**Comment by deepul80** [comment]
hey im deepanshu im unable to use plugins
this is the ss of issue i face since 4 days

**Comment by zorglube** [comment]
Hey @deepul80 can you be more specific ?

**Comment by deepul80** [comment]
What do you mean?

**Comment by zorglube** [comment]
I mean, if you want us to help you, you have to give us some information about the error you face.
