### ISSUE TITLE
FreeBSD 12.2 EOL

### ISSUE THREAD

**Issue by rs1278** [freenas/iocage-ix-plugins#312]
FreeBSD 12.2 is EOL as of tomorrow (3/31/2022), can we move these plugins to 12.3?

**Comment by amotin** [comment]
TrueNAS 12.0 is still based on FreeBSD 12.2 with some patches.  It is not guarantied to run 12.3 jails. The next version should be 13.1.

**Comment by rs1278** [comment]
roger that

**Comment by sonicaj** [comment]
@zorglube we will be updating plugins to use 12.3 which are not already doing in https://jira.ixsystems.com/browse/NAS-115743?atlLinkOrigin=c2xhY2staW50ZWdyYXRpb258aXNzdWU%3D. Closing this issue.

**Comment by zorglube** [comment]
Ok, gonna have a look for the MovieNight plugin.
