### ISSUE TITLE
Failed to install nextcloud in TrueNAS 13

### ISSUE THREAD

**Issue by littleneko** [freenas/iocage-ix-plugins#319]
the error msg:
```
Error: sssss had a failure Exception: RuntimeError Message: pkg error: - nginx : Refusing to fetch artifact and run post_install.sh! Partial plugin destroyed
```

The nginx is failed to install.

I try to change the jails release version to 12.3-RELEASE, it work well

**Comment by starkmapper** [comment]
The problem is that there is no more "nginx" package for FreeBSD 13:
![image](https://user-images.githubusercontent.com/944388/171591897-77a3b857-95f4-4916-9fad-73c44e1d8196.png)

https://pkgs.org/search/?q=%2Fusr%2Flocal%2Fsbin%2Fnginx

**Comment by littleneko** [comment]
the latest FreeBSD 13 has nginx package
