### ISSUE TITLE
Outdated Syncthing

### ISSUE THREAD

**Issue by somejavadev** [freenas/iocage-ix-plugins#325]
Hi,

What would the process be for getting an updated version of syncthing? The one currently running on Truenas Core 13 is version 1.18, the latest version of syncthing being  v1.20.4.

**Comment by sonicaj** [comment]
It has been updated, thanks!

**Comment by somejavadev** [comment]
Excellent, thank you very much!

![image](https://user-images.githubusercontent.com/6507120/187455647-b57d02da-a157-4250-866a-b2e4044e5937.png)  
  
![image](https://user-images.githubusercontent.com/6507120/187455824-595d50f8-bf46-4e85-80da-8cb992f04e0f.png)
