### ISSUE TITLE
 Unable to get plugins

### ISSUE THREAD

**Issue by rikingcn** [freenas/iocage-ix-plugins#330]
Error: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/middlewared/main.py", line 166, in call_method
    result = await self.middleware.call_method(self, message)
  File "/usr/local/lib/python3.6/site-packages/middlewared/main.py", line 1093, in call_method
    return await self._call(message['method'], serviceobj, methodobj, params, app=app, io_thread=False)
  File "/usr/local/lib/python3.6/site-packages/middlewared/main.py", line 1037, in _call
    return await self._call_worker(name, *args)
  File "/usr/local/lib/python3.6/site-packages/middlewared/main.py", line 1058, in _call_worker
    return await self.run_in_proc(main_worker, name, args, job)
  File "/usr/local/lib/python3.6/site-packages/middlewared/main.py", line 990, in run_in_proc
    return await async_run_in_executor(loop, executor, method, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/middlewared/utils/asyncio_.py", line 41, in async_run_in_executor
    raise result
RuntimeError: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v https://github.com/freenas/iocage-ix-plugins.git /mnt/cache/iocage/.plugin_index
  stderr: 'Cloning into '/mnt/cache/iocage/.plugin_index'...
fatal: unable to access 'https://github.com/freenas/iocage-ix-plugins.git/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 

Please help me solve this pending problem? thank you

![70d7299b033b5bb5ed7e6c3c73d3d539b400bcae](https://user-images.githubusercontent.com/118335523/202101525-9a331a4e-7b4b-40fb-ab1a-323f5358df02.jpg)
![54348c2397dda14497a72070f7b7d0a20ef486ad](https://user-images.githubusercontent.com/118335523/202101555-3e5bccae-7db3-44b6-8a68-8340dbe77dc8.jpg)

**Comment by turlodales** [comment]
im having the same problem but im in TrueNAS TrueNAS-13.0-U3.1

**Comment by gabshergit** [comment]
same here...im unable to install the plugins even after reinstalling TrueNas 13....it ain't working at all
please help us out to figure this Out

**Comment by sonicaj** [comment]
@gabshergit / @turlodales  / @rikingcn please create a ticket https://ixsystems.atlassian.net/jira here and kindly make sure your TrueNAS has internet access and is able to resolve domains (also do add a debug of your system to the ticket please).
