### ISSUE TITLE
NextCloud, updating trusted_domains from config.php not working

### ISSUE THREAD

**Issue by CostiFlorescu** [freenas/iocage-ix-plugins#332]
Hello, 

While updating config.php, trusted domains, Nextcloud is still not working as expected. 
I've added screenshot with config.php

Please
![NextCloud](https://user-images.githubusercontent.com/92465643/210005908-abab9b11-b737-4a6f-ae91-55200dce05b6.PNG)

**Comment by sonicaj** [comment]
@CostiFlorescu can you instead create an issue at https://ixsystems.atlassian.net please ? Thanks!
