### ISSUE TITLE
Plex plugin unable to install on TrueNAS-13.0-U3.1

### ISSUE THREAD

**Issue by gcodexman** [freenas/iocage-ix-plugins#336]
After upgrading to U3.1

Delete old PLEX plugin and reinstall it

Official Plugin

Version: 1.30.0.6486

Error: plex had a failure Exception: RuntimeError Message: pkg error: - ffmpeg : Refusing to fetch artifact and run post_install.sh! Partial plugin destroyed

Retried many times but it didn't work.

**Comment by sonicaj** [comment]
![Screenshot 2023-01-29 at 12 27 09 AM](https://user-images.githubusercontent.com/17968138/215287151-43ef9a60-7b13-4496-88f2-16a3f0f5d1e6.png)

I successfully installed plex. Please raise an issue in our bug tracker with a debug of your system if you are still unable to install it. Thanks!
