### ISSUE TITLE
PHP 8.1 for Nextcloud-Plugin?

### ISSUE THREAD

**Issue by PunchIng** [freenas/iocage-ix-plugins#348]
Is there a plan or schedule to upgrade the Nextcloud Plugin to PHP 8.1 or newer? My Nextcloud was updated to 27 and now complains about the "outdated" PHP 8.0...

**Comment by kmoore134** [comment]
I'll review any PRs that come in from the community, but at the moment I have no plans to do that myself. I'd strongly encourage any users running Nextcloud to use the proper container version on SCALE. I ran it as a plugin / jail for years myself and it was a never-ending struggle of time spent to chase these dependencies and the breakage that resulted. Container on SCALE is far more reliable for keeping up to date.

**Comment by PunchIng** [comment]
Any ideas how do I do it on CORE?

Am 08.08.23 um 19:21 schrieb Kris Moore:
> I'll review any PRs that come in from the community, but at the moment I have no plans to do that myself. I'd strongly encourage any users running Nextcloud to use the proper container version on SCALE. I ran it as a plugin / jail for years myself and it was a never-ending struggle of time spent to chase these dependencies and the breakage that resulted. Container on SCALE is far more reliable for keeping up to date.
>

**Comment by kmoore134** [comment]
Somebody has to update the JSON file for the plugin and change all the package versions, then deal with any breakages that result :)

https://github.com/freenas/iocage-ix-plugins/blob/master/nextcloud.json

**Comment by PunchIng** [comment]
... and that's probably something I should not try ...

Am 08.08.23 um 19:24 schrieb Kris Moore:
> Somebody has to update the JSON file for the plugin and change all the package versions, then deal with any breakages that result :)
> 
> https://github.com/freenas/iocage-ix-plugins/blob/master/nextcloud.json
>
