### ISSUE TITLE
Gitlab package was renamed

### ISSUE THREAD

**Issue by gronke** [freenas/iocage-ix-plugins#35]
The iocage Gitlab plugin does not properly install on FreeBSD 11 because the package `gitlab` was renamed to `gitlab-ce`.

https://svnweb.freebsd.org/ports?view=revision&revision=473925

**Comment by gronke** [comment]
I've found this issue while testing https://github.com/iocage/libiocage/pull/426 when manually provisioning random plugins on HardenedBSD and FreeBSD. I'm pointing to the release pkg releases for the major version (e.g. https://pkg.freebsd.org/FreeBSD:11:amd64/latest/).

It seems the package was renamed recently which is why we do not see it yet in quaterly releases or on HardenedBSD.

The issue was filed here because the packages to be installed come from the [gitlab.json#L6](https://github.com/freenas/iocage-ix-plugins/blob/9095798d91ad6ae4068bae8bc48085f470cd5457/gitlab.json#L6) file .

IMO the better location for listing the packages is in the artifacts repository. The problem can be solved by providing alternative packages, for instance notated like this:

```
"pkgs": [
    ["www/gitlab", "www/gitlab-ce"],
    "databases/postgresql95-server",
    "databases/postgresql95-contrib",
    "www/nginx"
  ],
```

The sample above could be interpreted as "Install www/gitlab or www/gitlab-ce if the first was not available". This approach assumes that there will be no other package www/gitlab in the future.

**Comment by miwi-fbsd** [comment]
Hi,
Yes but this isn't an error on the current iocage plugin, as long we link to the packages we provide for iocage all is good. Thank you for the heads up.

**Comment by gronke** [comment]
This is an error on systems run FreeBSD 11 and do not target quaterly releases - and there the issue will hit with just some delay. libiocage will allow the user to select the pkg source so that covering the changes now will not only prevent this from breaking on FreeNAS, but also solve the issue for libiocage now.

This kind of issue can occur any time to other packets and finding a way to deal with it now does not hurt more than it would be in 4 month. Do you intend being downwards compatible once the renaming to gitlab-ce was propagated to quaterly,

**Comment by miwi-fbsd** [comment]
Once again. Right now we're providing the plugins with our own set of packages,
as its is for now. Its on your own risk to link to an another repo with your own package set. Which is in my opinion totally fine but then you have to take also the responsibility to fix the plugin on your own. I do agree that we have to think about how to settle it in future when the times comes.

**Comment by gronke** [comment]
You will run into this issue in a couple of month from now. @william-gr has asked me to implement ix-iocage-plugin support in libiocage, so I suggest we define a list of targeted hosts. IMO this list should include the current major releases `Latest` package source, even though it is not yet used by FreeNAS.

**Comment by miwi-fbsd** [comment]
This should be sorted.
