### ISSUE TITLE
Plugin request: monicahq

### ISSUE THREAD

**Issue by jonblack** [freenas/iocage-ix-plugins#68]
I would like to propose a new plugin for [monicahq](https://www.monicahq.com/) - a personal CRM.

**Comment by miwi-fbsd** [comment]
Hi Jon,

Thanks for your proposal, this software is not ported yet to FreeBSD, I will see how quick I can do that.

**Comment by jonblack** [comment]
Thanks. If you need someone to test it on FreeNas please reach out.

**Comment by miwi-fbsd** [comment]
Hello, We have moved community plugins to https://github.com/ix-plugin-hub/iocage-plugin-index, can u please reopen the plugin request there. Thanks.
