### ISSUE TITLE
Nextcloud 15 recommend imagick php module. Not installed (and can't be installed?)

### ISSUE THREAD

**Issue by louizo** [freenas/iocage-ix-plugins#69]
Hello,

Since version 15.x, Nextcloud fresh install recommend imagick php module, but it does not seems to exist in iocage pkg repository.
I think it should be included in nextcloud-php71-15.0.0.txz package. (or repository should have php71-imagick package, so it can be added)

![image](https://user-images.githubusercontent.com/12612524/51559027-29a7fb80-1e81-11e9-8032-9f9ec873ea19.png)

I don't know how to change this packages, or if there is a github for this... let me know

**Comment by miwi-fbsd** [comment]
Hi,

Thanks for pointing that out. I have added graphics/pecl-imagick to the package list

**Comment by miwi-fbsd** [comment]
Problem is solved.
