### ISSUE TITLE
Plex Media Server is stuck a major version behind at 1.14.1.5488 (info)

### ISSUE THREAD

**Issue by arcooke** [freenas/iocage-ix-plugins#75]
Hi.  The Plex Media Server plugin cannot be updated beyond `1.14.1.5488`.  The latest on freshports is `1.15.1.710`.  People are trying to manually update due to the lack of official updates, and they're having issues.  Plex employees are involved and I just wanted to drop some info here to get it on your radar.

I don't know if it's related to the server version but my users are experiencing a lot of buffering problems despite low resource/bandwidth usage.  I currently cannot update to test, but if the server version is to blame, then this should be prioritized.

Please follow this thread for more info:

https://forums.plex.tv/t/i-updated-to-plexmediaserver-1-15-0-659-9311f93fd-and-now-i-cant-access-server-setting/377180

There's some chatter about API changes here:

https://forums.plex.tv/t/what-is-up-with-the-https-plex-tv-api-downloads-url/381916

I noticed from that thread that `https://plex.tv/api/downloads/1.json?channel=plexpass` shows the latest version as `1.14.1.5488`, which is what we're stuck at.  I don't know if there's any connection here, or if FreeNAS even uses the plex download api for version info in any capacity.  API v5 now requires [`X-Plex-Token`](https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/) or it will return an empty json object

Bad: `https://plex.tv/api/downloads/5.json?channel=plexpass`

Good: `https://plex.tv/api/downloads/5.json?channel=plexpass&X-Plex-Token=xxxxxxxxxxxxx`

**Comment by fryfrog** [comment]
1.14.1.5488 is the latest non-plexpass version, 1.15.1.710 is for plexpass.

**Comment by arcooke** [comment]
I was actually referring to plexpass.  Plexpass plugin pulls from trueos repo

https://github.com/freenas/iocage-ix-plugins/blob/master/plexmediaserver-plexpass.json

`/usr/local/etc/pkg/repos/iocage-plugins.conf`

```
iocage-plugins: {
    url: "http://pkg.cdn.trueos.org/iocage/11.2-RELEASE",
    signature_type: "fingerprints",
    fingerprints: "/usr/local/etc/pkg/fingerprints/iocage-plugins",
    enabled: true
}
```

Follow link: http://pkg.cdn.trueos.org/iocage/11.2-RELEASE/All/

You'll see plexpass is still on 1.14.x.  

![image](https://user-images.githubusercontent.com/6278400/54164272-0550b000-442a-11e9-8172-1b13150b2c7d.png)

Is there something I'm missing?

**Comment by fryfrog** [comment]
Should have minded my own business, sorry! Was here for something unrelated and thought I was being helpful! :)
