### ISSUE TITLE
Update Emby plugin to 4.0.2 (latest freshport) it finally works on FreeNAS again

### ISSUE THREAD

**Issue by bott0r** [freenas/iocage-ix-plugins#78]
Please Update the official Plugin repository, Emby 3.5 is depreciated and will not work, please update it to 4.0.2

Thanks

**Comment by dlavigne** [comment]
We currently have an open ticket (https://redmine.ixsystems.com/issues/70842) which is blocked due to the change in license (https://www.reddit.com/r/emby/comments/ah7083/emby_deleted_github_issues_regarding_gpl_and/).

**Comment by bott0r** [comment]
I was not aware. Thanks for the clarification!

**Comment by ma-karai** [comment]
According to the main lead of the emby project, emby is fully gpl compliant, so please reconsider to either update the current emby plugin or completely remove it from the freenas plugin repository.  As it stands the current available emby plugin does not work properly.

**Comment by miwi-fbsd** [comment]
Hi,

We do have http://pkg.cdn.trueos.org/iocage/unstable/All/emby-server-4.0.2.0_1.txz already updated. And in next weeks update will be 4.1.1.0 included.
