### ISSUE TITLE
sonarr.json contains wrong sha256 key

### ISSUE THREAD

**Issue by J-P-Bakker** [freenas/iocage-ix-plugins#85]
Hi,

In the sonarr.json the sha256 key is the same as that of radarr.json. When installing sonarr it will only find radarr (and install radarr). 

When looking in packagesite.yaml from http://pkg.cdn.trueos.org/iocage/unstable/ the sha256 code for sonarr should be: cd2327e92c89b3d91ff0e1a81752e481e7c8558aadb8b605d3cda4c493aa2204

**Comment by miwi-fbsd** [comment]
This should be fixed.
