### ISSUE TITLE
[gitlab] gitlab:backup:restore rake task requires GNU tar

### ISSUE THREAD

**Issue by djpadz** [freenas/iocage-ix-plugins#96]
`rake gitlab:backup:restore` will fail when restoring a backup, because `/usr/local/www/gitlab-ce/lib/backup/files.rb` requires GNU tar.

Verified by doing the following:

```sh
# cd /usr/local/etc/pkg/repos
# mv FreeBSD.conf FreeBSD.conf.bak
# pkg install gtar
# mv FreeBSD.conf.bak FreeBSD.conf
# cd /usr/local/www/gitlab-ce
# su git -c 'bundle exec rake gitlab:backup:restore RAILS_ENV=production force=yes'
```

**Comment by djpadz** [comment]
I should say that I verified that it fails without `gtar` installed.  That's what started this whole thing :-)

**Comment by miwi-fbsd** [comment]
Thanks for heads up. I will fix it asap.
